<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.*" />
    <PackageReference Include="Dapper.Contrib" Version="2.*" />
    <PackageReference Include="DapperExtensions" Version="1.*" />
    <PackageReference Include="Npgsql" Version="8.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lore.Basvuru.Common\Lore.Basvuru.Common.csproj" />
  </ItemGroup>
</Project>
