<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.*" />
    <PackageReference Include="Minio" Version="6.*" />
    <PackageReference Include="Newtonsoft.Json" Version="13.*" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.*" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lore.Basvuru.Dal\Lore.Basvuru.Dal.csproj" />
    <ProjectReference Include="..\Lore.Basvuru.Common\Lore.Basvuru.Common.csproj" />
  </ItemGroup>
</Project>
